name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build (Make Debug)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Make and Dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build (Debug)
        run: make

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install Make and Dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Tests
        run: make test

